pipeline {
    agent any
    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/LadaniDhara/ITC_BD/tree/muazrana'
            }
        }
        stage('Run PySpark ETL') {
            steps {
                sh 'python etl_transformation/hive_etl.py'
            }
        }
    }
}
